### ISSUE TITLE
JKO updated

### ISSUE THREAD

**Issue by 420BlazeItFags** [Clutch152/scripts#1]
JKO has updated and the script no longer works because the course is flagged as suspicious soon completion.

**Comment by jotero6933** [comment]
Is there any update for the JKO's Script since it's not working anymore?

**Comment by Clutch152** [comment]
It is only flagged a suspicious for the test. If you use it up to a test then it still works just fine. I most cases on JKO you can usually just select random answers and any of the correct answers are removed from the next test and you can effectively chip away at them until you get a passing score. It usually doesn't take very long to do that either.

I looked into it but couldn't find anything tbh as to what causes the flag in the first place to bypass. The only reason these worked in the first place is because they left the code out in the open for people to read if they knew where/how to look but they may have gotten wise to that and hid the code so that it isn't viewable from the developer console.

**Comment by Jwboucher94** [comment]
As a side note - I was having an issue with one course, which at first I tried completing using this then just breezed through it and completed the test first try. It was still flagged for suspicious activity, so I called jko.
Turns out, they check the amount of time you spend looking at the content. If it doesn't exceed a certain minimum time, it will flag it. I've found roughly 1/3 of the time works best. This is also only for DL point courses.
