### ISSUE TITLE
Skillport added a time now 

### ISSUE THREAD

**Issue by GEFORCERTX** [Clutch152/scripts#61]
Does anyone have an update code for Skillport? I recently went on it and it allows me to pass the classes but in order for me to complete the assignment it have to complete the required time.

**Comment by TheRealGloxk** [comment]
@GEFORCERTX Is this still working?  I haven't been able to get any of the scripts to work.. I just was using it a month ago trying to find an updated version.

**Comment by TyrantRex** [comment]
![littlehint2](https://user-images.githubusercontent.com/5766919/173286102-59791f31-10b6-4c91-97c2-db3f1f3e2d09.png)
![littlehint](https://user-images.githubusercontent.com/5766919/173286090-60ad33a4-6a1a-4062-8870-76a1b7c44711.png)
That's a random number generator and a hint on how to get around it. Can't give it to you guys right now since I'm waiting on two more people to get their hours up. They deactivate your account if you do an abnormal amount of lessons per day now.

**Comment by TyrantRex** [comment]
@GEFORCERTX Yes. I don’t have access to the site anymore but, afaik, the new script is still working. 

What I gave you in the previous post was the bypass to get around the 20 minute wait. The guys using it rn are working on maxing out their hours. I’ll pass it along when they’re done

**Comment by TyrantRex** [comment]
It's similar but not quite. It's a little harder to retrieve lesson data but not impossible. The chrome dev console in F12 will help out greatly. The duration (in seconds) is what they're checking for on that last flag before the course test is enabled. That's why the random number generator is creating a value between 120 and 150. 

120 * 10 = 1200 seconds (20 minutes)
150 * 10 = 1500 seconds (25 minutes)

**Comment by doorbelldeadpool** [comment]
Can I get the updated script @TyrantRex @GEFORCERTX 

Teejay100detail@gmail.com 👀

**Comment by jjaajm666** [comment]
could i also get the updated script plz
jjaajm666@yahoo.com

**Comment by slycooper724** [comment]
@TyrantRex If you could kindly send the updated script to temporal_end7950@protonmail.com that would be great. I missed it when you sent it last time, and by the time I saw the email it had been taken down by you.

**Comment by Arodriguez496** [comment]
@TyrantRex If there even is any script that you know of that works could you send it my way grandmaster @TyrantRex. I am in need of these so called correspondence hours.  Email is: ballots.plural_0h@icloud.com Thank you.

**Comment by TyrantRex** [comment]
@jjaajm666 @slycooper724 @Arodriguez496 @appleking123 @doorbelldeadpool 
https://github.com/Clutch152/scripts/blob/master/Skillport/skillport_breaker.user.js

An update was pushed out a couple of weeks ago lol

**Comment by iEatNoodlez** [comment]
This discussion has been closed due to the upgrade of percipio.
